const givenText = [
    "șase sași în șase saci",
    "O babă bălană mănâncă o banană babană.",
    "Stânca stă-n castan ca saşa Stan",
    "Cupă cu capac, capac cu cupă.",
    "Pe cap un capac, pe capac un ac.",
    "Noi nu ne nimeriserăm minunăţiile lănţişoarelor remunerate",
    "Clopotarul clătina clopotul clopotniței.",
    "Retevei de tei pe mirişte de mei.",
    "Zecele de pică mare are masa la picioare.",
    'Unui tâmplar i s-a întâmplat o întâmplare. \nAlt tâmplar, auzind de întâmplarea tâmplarului \nde la tâmplărie, a venit și s-a lovit cu tâmpla de \n tâmplăria tâmplarului cu întâmplarea',
    "Domnule dudar, dă-mi două dude dulci din dudul dumitale de dincolo de Dunăre!",
    "O barză brează face zarvă pe-o varză",
    "Nașpa, nasol stau în nămol ca un actor jucând un rol!",
    "Capra calca-n piatra,Piatra crapa-n patru; Crăpa-i-ar capul caprei, Precum a crapat piatra-n patru.",
    "Un vultur stă pe-un pisc c-un pix în plisc",
    "Prin Vulturi vântul viu vuia",
    "Leul lăudat lipește abțibilduri lucioase.",
    "Sasha şuşotea șosetelor însuşiri şiruitoare.",
    "Bucur și Bucura se bucură că Bucurel e bucuros în București.",
    "Am o prepeliţă pestriţă cu paisprezece pui de prepeliţă pestriţi. E mai pestriţă prepeliţa pestriţă decât cei paisprezece pui de prepeliţă pestriţi.",
    "O coropișniță și-un coropișnițoi se coropișniteau la noi pe gunoi. Nu coropișnița coropișnițea pe coropișnițoi, ci coropișnițoiul coropișnițea pe coropișniță.",
  ]; // Set your desired text here

  export default givenText